bundler_args: --without development

rvm: 1.9.3

before_script: sh -e /etc/init.d/xvfb start

env:
  TEST=1
  TEST=2
  TEST=3
  TEST=4
  TEST=5
  TEST=6
  TEST=7
  TEST=8
  TEST=9

script:
  - "firefox --version"
  - "cp config/database.yml.example config/database.yml 2>&1"
  - "bundle exec rake db:drop db:create db:schema:load --trace"
  - "DISPLAY=:99.0 bundle exec rspec spec/requests"
