bundler_args: --without development

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - ree

before_script: sh -e /etc/init.d/xvfb start

#env: RAILS_ENV=travis

script:
  - "firefox --version"
  - "cp config/database.yml.example config/database.yml 2>&1"
  - "bundle exec rake db:drop db:create db:schema:load --trace"
  - "DISPLAY=:99.0 bundle exec rspec spec/requests"
